### ISSUE TITLE
handlePoolCreated Event Handler

### ISSUE THREAD

**Issue by Pochetes** [gammaswap/v0-subgraph#10]
## Structure
1. Creating (if first pool) or loading `GSFactory` entity. Abstract into a function with the following signature:
```typescript
function loadOrCreateFactory(event: PoolCreated): string | null
```
return the `poolAddress`
2. Create token entity for each reserve token in pool. Abstract into a function with the following signature:
```typescript
function getOrCreateERC20Token(event: ethereum.Event, address: Address): Token
```
3. Create new pool entity and load in all the values given by event, if not used initialize to zero BD

4. create pool template and save all of the entities and create

**Comment by fhd1423** [comment]
how am i getting the token addresses from the event? Can I get it from the event.transaction.input from this function? ```createPool(uint16 protocolId, address cfmm, address[] calldata tokens) external returns(address)```

**Comment by Pochetes** [comment]
> how am i getting the token addresses from the event?

So @dam417 is going to update the `PoolCreated` to be
```solidity
event PoolCreated(uint256[] tokens, address pool, address cfmm, uint24 implementationID)
```

they would have addresses and then you would have to make a token entity off of it.

just focus on getting the logic correct as much as you can until you can update the ABIs

**Comment by Pochetes** [comment]
The `loadOrCreateFactory` function should be in replace of the function you have called `handlePoolCreatedForOverview`. This should be done before creating the pool.

It should be:
1. GSFactory
2. tokens
3. pools

**Comment by Pochetes** [comment]
The new `PoolCreated` event looks like this
```solidity
event PoolCreated(address indexed pool, address indexed cfmm, uint16 indexed protocolId, address implementation, address[] tokens, uint256 count)
```

So now the steps for `handlePoolCreated` will be:
1. `createOrLoadFactory` function
    * load the factory with `FACTORY_ADDRESS` macro variable
    * zero initialize the properties
    * the event will pass in `count` but just add 1 to the current pair count for now
    * save the factory
2. get or create tokens
    * similar structure to the previous function, but loading it with the token address passed from the event
    * implement `getOrLoadERC20Token` func, return the token if exists, otherwise bind the address to an ERC20 contract and use the `try_` functions to fetch the name, symbol and decimals ([resource](https://thegraph.com/docs/en/developing/assemblyscript-api/#handling-reverted-calls)), then save and return it.
    * do this for each token
3. create new pool entity
    * similar structure to the factory function, but with the pool entity `getOrCreatePool`
    * return the pool
4. instantiate pool data source (`PoolTemplate.create(event.params.pool`)
5. Save everything
